name: "Nix build"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          system-features = kvm nixos-test
    - name: Show flake metadata
      run: nix flake info
    - name: Build linguee-api
      run: nix build .#linguee-api
    - name: Run flake checks
      run: |
        nix flake check \
        --show-trace \
        --print-build-logs \
        --option allow-import-from-derivation true
